mod referencepointtypein;
mod virtualsystemreferencepointservice;
mod virtualsystemreferencepointserviceout;
mod virtualsystemreferencepointsettingdatain;

pub(crate) use referencepointtypein::ReferencePointTypeIn;
pub(crate) use virtualsystemreferencepointservice::VirtualSystemReferencePointService;
use virtualsystemreferencepointserviceout::VirtualSystemReferencePointServiceOut;
pub(crate) use virtualsystemreferencepointsettingdatain::VirtualSystemReferencePointSettingDataIn;
