use serde::Deserialize;
use wmi::{WMIDateTime, WMIDuration};

#[derive(Debug, Deserialize)]
#[allow(non_snake_case)]
pub(super) struct JobOut {
    pub(super) Cancellable: bool,
    pub(super) Caption: String,
    pub(super) CommunicationStatus: Option<u16>,
    pub(super) DeleteOnCompletion: bool,
    pub(super) Description: String,
    pub(super) DetailedStatus: Option<u16>,
    pub(super) ElapsedTime: WMIDuration,
    pub(super) ElementName: String,
    pub(super) ErrorCode: u16,
    pub(super) ErrorDescription: String,
    pub(super) ErrorSummaryDescription: String,
    pub(super) HealthState: u16,
    pub(super) InstallDate: WMIDateTime,
    pub(super) InstanceID: String,
    pub(super) JobRunTimes: u32,
    pub(crate) JobState: u16,
    pub(super) JobStatus: String,
    pub(super) JobType: u16,
    pub(super) LocalOrUtcTime: u16,
    pub(super) Name: String,
    pub(super) Notify: String,
    pub(super) OperatingStatus: Option<u16>,
    pub(super) OperationalStatus: Vec<u16>,
    pub(super) OtherRecoveryAction: String,
    pub(super) Owner: String,
    pub(super) PercentComplete: u16,
    pub(super) Priority: u32,
    pub(super) PrimaryStatus: Option<u16>,
    pub(super) RecoveryAction: u16,
    pub(super) RunMonth: Option<u8>,
    pub(super) RunDay: Option<i8>,
    pub(super) RunDayOfWeek: Option<i8>,
    pub(super) RunStartInterval: Option<WMIDuration>,
    pub(super) ScheduledStartTime: WMIDateTime,
    pub(super) StartTime: WMIDateTime,
    pub(super) Status: String,
    pub(super) StatusDescriptions: Vec<String>,
    pub(super) TimeOfLastStateChange: WMIDateTime,
    pub(super) TimeSubmitted: WMIDateTime,
    pub(super) TimeBeforeRemoval: WMIDuration,
    pub(super) UntilTime: Option<WMIDateTime>,
}
