use serde::Deserialize;

#[derive(Debug)]
pub(super) enum JobType {
    Unknown,
    DefineVirtualMachine,
    ModifyVirtualMachine,
    DestroyVirtualMachine,
    ModifyManagementServiceSettings,
    InitializeVirtualMachine,
    WaitingToStartVirtualMachine,
    StartVirtualMachine,
    PowerOffVirtualMachine,
    SaveVirtualMachine,
    RestoreVirtualMachine,
    ShutDownVirtualMachine,
    PauseVirtualMachine,
    ResumeVirtualMachine,
    ResetVirtualMachine,
    RebootVirtualMachine,
    AddVirtualMachineResources,
    ModifyVirtualMachineResources,
    RemoveVirtualMachineResources,
    RequestInitialVirtualMachineMemory,
    AddMemoryToVirtualMachine,
    RemoveMemoryFromVirtualMachine,
    MergingVHDDisks,
    CreateVSSSnapshotInsideVirtualMachine,
    GetImportSettingData,
    ImportVirtualMachine,
    ExportVirtualMachine,
    RegisterConfiguration,
    UnregisterConfiguration,
    SnapshotVirtualMachine,
    ApplyVirtualMachineSnapshot,
    DeleteVirtualMachineSnapshot,
    ClearVirtualMachineSnapshotState,
    AddResourceToResourcePool,
    RemoveResourceFromResourcePool,
    ModifyReplicationServerSettings,
    CreateReplicationRelationship,
    ModifyReplicationRelationshipSettings,
    RemoveReplicationRelationship,
    StartInbandInitialReplication,
    ImportReplication,
    ReplicateStateChange,
    InitiateFailover,
    RevertFailover,
    CommitFailover,
    InitiateSyncedReplication,
    CancelSyncedReplication,
    InitiateTestReplica,
    RemoveTestReplica,
    ReverseReplication,
    ReplicationSendingDelta,
    ReplicationReceivingDelta,
    Resynchronizing,
    ApplyChangeLog,
    StopInitialReplication,
    StopResynchronizing,
    GetReplicaStatistics,
    PrepareForConsistencyChecker,
    ConsistencyChecker,
    StopConsistencyChecker,
    TestReplicationConnection,
    SendingInitialReplica,
    StartResyncInitialReplication,
    StartExportInitialReplication,
    ResetReplicaStatistics,
    ApplyRegisteredDeltas,
    ResynchronizingExtendedReplication,
    ReadingTestReplicaConfiguration,
    ChangeReplicationModeToPrimary,
    InitiateFailback,
    UpdateDiskSet,
    DefineEthernetSwitch,
    ModifyEthernetSwitchSettings,
    DestroyEthernetSwitch,
    AddEthernetSwitchResources,
    ModifyEthernetSwitchResources,
    RemoveEthernetSwitchResources,
    ValidatePlannedVirtualMachine,
    RealizingVirtualMachine,
    CreatingResourcePool,
    ChangingParentResourcesOfResourcePool,
    ChangingNonAllocationSettingsOfResourcePool,
    DeletingResourcePool,
    EnableRemoteFxGpu,
    DisableRemoteFxGpu,
    Modify3DServiceSettings,
    BackupVirtualMachine,
    GuestServiceInterface,
    QueryGuestClusterInformation,
    DefineCollection,
    DestroyCollection,
    RenameCollection,
    AddMemberToCollection,
    RemoveMemberFromCollection,
    AddSettingToCollection,
    RemoveSettingFromCollection,
    ModifySettingOnCollection,
    SnapshotCollection,
    ConvertSnapshotToReferencePoint,
    CreateReferencePoint,
    DeleteReferencePoint,
    ExportReferencePoint,
    RemoveAssociatedDataFromReferencePoint,
    CreateReferencePointOnCollection,
    ExportReferencePointOnCollection,
    RemoveAssociatedDataFromReferencePointOnCollection,
    DeleteReferencePointOnCollection,
    ImportReferencePointMetadata,
    MountOrDismountAssignableDevice,
}

impl TryFrom<u16> for JobType {
    type Error = &'static str;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::DefineVirtualMachine),
            2 => Ok(Self::ModifyVirtualMachine),
            3 => Ok(Self::DestroyVirtualMachine),
            4 => Ok(Self::ModifyManagementServiceSettings),
            10 => Ok(Self::InitializeVirtualMachine),
            11 => Ok(Self::WaitingToStartVirtualMachine),
            12 => Ok(Self::StartVirtualMachine),
            13 => Ok(Self::PowerOffVirtualMachine),
            14 => Ok(Self::SaveVirtualMachine),
            15 => Ok(Self::RestoreVirtualMachine),
            16 => Ok(Self::ShutDownVirtualMachine),
            26 => Ok(Self::PauseVirtualMachine),
            27 => Ok(Self::ResumeVirtualMachine),
            28 => Ok(Self::ResetVirtualMachine),
            29 => Ok(Self::RebootVirtualMachine),
            30 => Ok(Self::AddVirtualMachineResources),
            31 => Ok(Self::ModifyVirtualMachineResources),
            32 => Ok(Self::RemoveVirtualMachineResources),
            40 => Ok(Self::RequestInitialVirtualMachineMemory),
            41 => Ok(Self::AddMemoryToVirtualMachine),
            42 => Ok(Self::RemoveMemoryFromVirtualMachine),
            50 => Ok(Self::MergingVHDDisks),
            51 => Ok(Self::CreateVSSSnapshotInsideVirtualMachine),
            60 => Ok(Self::GetImportSettingData),
            61 => Ok(Self::ImportVirtualMachine),
            62 => Ok(Self::ExportVirtualMachine),
            63 => Ok(Self::RegisterConfiguration),
            64 => Ok(Self::UnregisterConfiguration),
            70 => Ok(Self::SnapshotVirtualMachine),
            71 => Ok(Self::ApplyVirtualMachineSnapshot),
            72 => Ok(Self::DeleteVirtualMachineSnapshot),
            73 => Ok(Self::ClearVirtualMachineSnapshotState),
            80 => Ok(Self::AddResourceToResourcePool),
            81 => Ok(Self::RemoveResourceFromResourcePool),
            90 => Ok(Self::ModifyReplicationServerSettings),
            91 => Ok(Self::CreateReplicationRelationship),
            92 => Ok(Self::ModifyReplicationRelationshipSettings),
            93 => Ok(Self::RemoveReplicationRelationship),
            94 => Ok(Self::StartInbandInitialReplication),
            95 => Ok(Self::ImportReplication),
            96 => Ok(Self::ReplicateStateChange),
            97 => Ok(Self::InitiateFailover),
            98 => Ok(Self::RevertFailover),
            99 => Ok(Self::CommitFailover),
            100 => Ok(Self::InitiateSyncedReplication),
            101 => Ok(Self::CancelSyncedReplication),
            102 => Ok(Self::InitiateTestReplica),
            103 => Ok(Self::RemoveTestReplica),
            104 => Ok(Self::ReverseReplication),
            105 => Ok(Self::ReplicationSendingDelta),
            106 => Ok(Self::ReplicationReceivingDelta),
            107 => Ok(Self::Resynchronizing),
            108 => Ok(Self::ApplyChangeLog),
            109 => Ok(Self::StopInitialReplication),
            110 => Ok(Self::StopResynchronizing),
            111 => Ok(Self::GetReplicaStatistics),
            112 => Ok(Self::PrepareForConsistencyChecker),
            113 => Ok(Self::ConsistencyChecker),
            114 => Ok(Self::StopConsistencyChecker),
            115 => Ok(Self::TestReplicationConnection),
            116 => Ok(Self::SendingInitialReplica),
            117 => Ok(Self::StartResyncInitialReplication),
            118 => Ok(Self::StartExportInitialReplication),
            119 => Ok(Self::ResetReplicaStatistics),
            120 => Ok(Self::ApplyRegisteredDeltas),
            121 => Ok(Self::ResynchronizingExtendedReplication),
            122 => Ok(Self::ReadingTestReplicaConfiguration),
            123 => Ok(Self::ChangeReplicationModeToPrimary),
            124 => Ok(Self::InitiateFailback),
            125 => Ok(Self::UpdateDiskSet),
            130 => Ok(Self::DefineEthernetSwitch),
            131 => Ok(Self::ModifyEthernetSwitchSettings),
            132 => Ok(Self::DestroyEthernetSwitch),
            133 => Ok(Self::AddEthernetSwitchResources),
            134 => Ok(Self::ModifyEthernetSwitchResources),
            135 => Ok(Self::RemoveEthernetSwitchResources),
            140 => Ok(Self::ValidatePlannedVirtualMachine),
            141 => Ok(Self::RealizingVirtualMachine),
            150 => Ok(Self::CreatingResourcePool),
            151 => Ok(Self::ChangingParentResourcesOfResourcePool),
            152 => Ok(Self::ChangingNonAllocationSettingsOfResourcePool),
            153 => Ok(Self::DeletingResourcePool),
            160 => Ok(Self::EnableRemoteFxGpu),
            161 => Ok(Self::DisableRemoteFxGpu),
            162 => Ok(Self::Modify3DServiceSettings),
            170 => Ok(Self::BackupVirtualMachine),
            180 => Ok(Self::GuestServiceInterface),
            181 => Ok(Self::QueryGuestClusterInformation),
            190 => Ok(Self::DefineCollection),
            191 => Ok(Self::DestroyCollection),
            192 => Ok(Self::RenameCollection),
            193 => Ok(Self::AddMemberToCollection),
            194 => Ok(Self::RemoveMemberFromCollection),
            195 => Ok(Self::AddSettingToCollection),
            196 => Ok(Self::RemoveSettingFromCollection),
            197 => Ok(Self::ModifySettingOnCollection),
            198 => Ok(Self::SnapshotCollection),
            200 => Ok(Self::ConvertSnapshotToReferencePoint),
            201 => Ok(Self::CreateReferencePoint),
            202 => Ok(Self::DeleteReferencePoint),
            203 => Ok(Self::ExportReferencePoint),
            204 => Ok(Self::RemoveAssociatedDataFromReferencePoint),
            205 => Ok(Self::CreateReferencePointOnCollection),
            206 => Ok(Self::ExportReferencePointOnCollection),
            207 => Ok(Self::RemoveAssociatedDataFromReferencePointOnCollection),
            208 => Ok(Self::DeleteReferencePointOnCollection),
            209 => Ok(Self::ImportReferencePointMetadata),
            260 => Ok(Self::MountOrDismountAssignableDevice),
            _ => Err("Unsupported job state"),
        }
    }
}

impl<'de> Deserialize<'de> for JobType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Self::try_from(u16::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}
