use serde::Deserialize;

#[derive(Debug)]
pub(super) enum JobType {
    Unknown,
    DefineVirtualMachine,
    ModifyVirtualMachine,
    DestroyVirtualMachine,
    ModifyManagementServiceSettings,
    InitializeVirtualMachine,
    WaitingToStartVirtualMachine,
    StartVirtualMachine,
    PowerOffVirtualMachine,
    SaveVirtualMachine,
    RestoreVirtualMachine,
    ShutDownVirtualMachine,
    PauseVirtualMachine,
    ResumeVirtualMachine,
    ResetVirtualMachine,
    RebootVirtualMachine,
    AddVirtualMachineResources,
    ModifyVirtualMachineResources,
    RemoveVirtualMachineResources,
    RequestInitialVirtualMachineMemory,
    AddMemoryToVirtualMachine,
    RemoveMemoryFromVirtualMachine,
    MergingVHDDisks,
    CreateVSSSnapshotInsideVirtualMachine,
    GetImportSettingData,
    ImportVirtualMachine,
    ExportVirtualMachine,
    RegisterConfiguration,
    UnregisterConfiguration,
    SnapshotVirtualMachine,
    ApplyVirtualMachineSnapshot,
    DeleteVirtualMachineSnapshot,
    ClearVirtualMachineSnapshotState,
    AddResourceToResourcePool,
    RemoveResourceFromResourcePool,
    ModifyReplicationServerSettings,
    CreateReplicationRelationship,
    ModifyReplicationRelationshipSettings,
    RemoveReplicationRelationship,
    StartInbandInitialReplication,
    ImportReplication,
    ReplicateStateChange,
    InitiateFailover,
    RevertFailover,
    CommitFailover,
    InitiateSyncedReplication,
    CancelSyncedReplication,
    InitiateTestReplica,
    RemoveTestReplica,
    ReverseReplication,
    ReplicationSendingDelta,
    ReplicationReceivingDelta,
    Resynchronizing,
    ApplyChangeLog,
    StopInitialReplication,
    StopResynchronizing,
    GetReplicaStatistics,
    PrepareForConsistencyChecker,
    ConsistencyChecker,
    StopConsistencyChecker,
    TestReplicationConnection,
    SendingInitialReplica,
    StartResyncInitialReplication,
    StartExportInitialReplication,
    ResetReplicaStatistics,
    ApplyRegisteredDeltas,
    ResynchronizingExtendedReplication,
    ReadingTestReplicaConfiguration,
    ChangeReplicationModeToPrimary,
    InitiateFailback,
    UpdateDiskSet,
    DefineEthernetSwitch,
    ModifyEthernetSwitchSettings,
    DestroyEthernetSwitch,
    AddEthernetSwitchResources,
    ModifyEthernetSwitchResources,
    RemoveEthernetSwitchResources,
    ValidatePlannedVirtualMachine,
    RealizingVirtualMachine,
    CreatingResourcePool,
    ChangingParentResourcesOfResourcePool,
    ChangingNonAllocationSettingsOfResourcePool,
    DeletingResourcePool,
    EnableRemoteFxGpu,
    DisableRemoteFxGpu,
    Modify3DServiceSettings,
    BackupVirtualMachine,
    GuestServiceInterface,
    QueryGuestClusterInformation,
    DefineCollection,
    DestroyCollection,
    RenameCollection,
    AddMemberToCollection,
    RemoveMemberFromCollection,
    AddSettingToCollection,
    RemoveSettingFromCollection,
    ModifySettingOnCollection,
    SnapshotCollection,
    ConvertSnapshotToReferencePoint,
    CreateReferencePoint,
    DeleteReferencePoint,
    ExportReferencePoint,
    RemoveAssociatedDataFromReferencePoint,
    CreateReferencePointOnCollection,
    ExportReferencePointOnCollection,
    RemoveAssociatedDataFromReferencePointOnCollection,
    DeleteReferencePointOnCollection,
    ImportReferencePointMetadata,
    MountOrDismountAssignableDevice,
}

impl TryFrom<u16> for JobType {
    type Error = &'static str;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(JobType::Unknown),
            1 => Ok(JobType::DefineVirtualMachine),
            2 => Ok(JobType::ModifyVirtualMachine),
            3 => Ok(JobType::DestroyVirtualMachine),
            4 => Ok(JobType::ModifyManagementServiceSettings),
            10 => Ok(JobType::InitializeVirtualMachine),
            11 => Ok(JobType::WaitingToStartVirtualMachine),
            12 => Ok(JobType::StartVirtualMachine),
            13 => Ok(JobType::PowerOffVirtualMachine),
            14 => Ok(JobType::SaveVirtualMachine),
            15 => Ok(JobType::RestoreVirtualMachine),
            16 => Ok(JobType::ShutDownVirtualMachine),
            26 => Ok(JobType::PauseVirtualMachine),
            27 => Ok(JobType::ResumeVirtualMachine),
            28 => Ok(JobType::ResetVirtualMachine),
            29 => Ok(JobType::RebootVirtualMachine),
            30 => Ok(JobType::AddVirtualMachineResources),
            31 => Ok(JobType::ModifyVirtualMachineResources),
            32 => Ok(JobType::RemoveVirtualMachineResources),
            40 => Ok(JobType::RequestInitialVirtualMachineMemory),
            41 => Ok(JobType::AddMemoryToVirtualMachine),
            42 => Ok(JobType::RemoveMemoryFromVirtualMachine),
            50 => Ok(JobType::MergingVHDDisks),
            51 => Ok(JobType::CreateVSSSnapshotInsideVirtualMachine),
            60 => Ok(JobType::GetImportSettingData),
            61 => Ok(JobType::ImportVirtualMachine),
            62 => Ok(JobType::ExportVirtualMachine),
            63 => Ok(JobType::RegisterConfiguration),
            64 => Ok(JobType::UnregisterConfiguration),
            70 => Ok(JobType::SnapshotVirtualMachine),
            71 => Ok(JobType::ApplyVirtualMachineSnapshot),
            72 => Ok(JobType::DeleteVirtualMachineSnapshot),
            73 => Ok(JobType::ClearVirtualMachineSnapshotState),
            80 => Ok(JobType::AddResourceToResourcePool),
            81 => Ok(JobType::RemoveResourceFromResourcePool),
            90 => Ok(JobType::ModifyReplicationServerSettings),
            91 => Ok(JobType::CreateReplicationRelationship),
            92 => Ok(JobType::ModifyReplicationRelationshipSettings),
            93 => Ok(JobType::RemoveReplicationRelationship),
            94 => Ok(JobType::StartInbandInitialReplication),
            95 => Ok(JobType::ImportReplication),
            96 => Ok(JobType::ReplicateStateChange),
            97 => Ok(JobType::InitiateFailover),
            98 => Ok(JobType::RevertFailover),
            99 => Ok(JobType::CommitFailover),
            100 => Ok(JobType::InitiateSyncedReplication),
            101 => Ok(JobType::CancelSyncedReplication),
            102 => Ok(JobType::InitiateTestReplica),
            103 => Ok(JobType::RemoveTestReplica),
            104 => Ok(JobType::ReverseReplication),
            105 => Ok(JobType::ReplicationSendingDelta),
            106 => Ok(JobType::ReplicationReceivingDelta),
            107 => Ok(JobType::Resynchronizing),
            108 => Ok(JobType::ApplyChangeLog),
            109 => Ok(JobType::StopInitialReplication),
            110 => Ok(JobType::StopResynchronizing),
            111 => Ok(JobType::GetReplicaStatistics),
            112 => Ok(JobType::PrepareForConsistencyChecker),
            113 => Ok(JobType::ConsistencyChecker),
            114 => Ok(JobType::StopConsistencyChecker),
            115 => Ok(JobType::TestReplicationConnection),
            116 => Ok(JobType::SendingInitialReplica),
            117 => Ok(JobType::StartResyncInitialReplication),
            118 => Ok(JobType::StartExportInitialReplication),
            119 => Ok(JobType::ResetReplicaStatistics),
            120 => Ok(JobType::ApplyRegisteredDeltas),
            121 => Ok(JobType::ResynchronizingExtendedReplication),
            122 => Ok(JobType::ReadingTestReplicaConfiguration),
            123 => Ok(JobType::ChangeReplicationModeToPrimary),
            124 => Ok(JobType::InitiateFailback),
            125 => Ok(JobType::UpdateDiskSet),
            130 => Ok(JobType::DefineEthernetSwitch),
            131 => Ok(JobType::ModifyEthernetSwitchSettings),
            132 => Ok(JobType::DestroyEthernetSwitch),
            133 => Ok(JobType::AddEthernetSwitchResources),
            134 => Ok(JobType::ModifyEthernetSwitchResources),
            135 => Ok(JobType::RemoveEthernetSwitchResources),
            140 => Ok(JobType::ValidatePlannedVirtualMachine),
            141 => Ok(JobType::RealizingVirtualMachine),
            150 => Ok(JobType::CreatingResourcePool),
            151 => Ok(JobType::ChangingParentResourcesOfResourcePool),
            152 => Ok(JobType::ChangingNonAllocationSettingsOfResourcePool),
            153 => Ok(JobType::DeletingResourcePool),
            160 => Ok(JobType::EnableRemoteFxGpu),
            161 => Ok(JobType::DisableRemoteFxGpu),
            162 => Ok(JobType::Modify3DServiceSettings),
            170 => Ok(JobType::BackupVirtualMachine),
            180 => Ok(JobType::GuestServiceInterface),
            181 => Ok(JobType::QueryGuestClusterInformation),
            190 => Ok(JobType::DefineCollection),
            191 => Ok(JobType::DestroyCollection),
            192 => Ok(JobType::RenameCollection),
            193 => Ok(JobType::AddMemberToCollection),
            194 => Ok(JobType::RemoveMemberFromCollection),
            195 => Ok(JobType::AddSettingToCollection),
            196 => Ok(JobType::RemoveSettingFromCollection),
            197 => Ok(JobType::ModifySettingOnCollection),
            198 => Ok(JobType::SnapshotCollection),
            200 => Ok(JobType::ConvertSnapshotToReferencePoint),
            201 => Ok(JobType::CreateReferencePoint),
            202 => Ok(JobType::DeleteReferencePoint),
            203 => Ok(JobType::ExportReferencePoint),
            204 => Ok(JobType::RemoveAssociatedDataFromReferencePoint),
            205 => Ok(JobType::CreateReferencePointOnCollection),
            206 => Ok(JobType::ExportReferencePointOnCollection),
            207 => Ok(JobType::RemoveAssociatedDataFromReferencePointOnCollection),
            208 => Ok(JobType::DeleteReferencePointOnCollection),
            209 => Ok(JobType::ImportReferencePointMetadata),
            260 => Ok(JobType::MountOrDismountAssignableDevice),
            _ => Err("Unsupported job state"),
        }
    }
}

impl<'de> Deserialize<'de> for JobType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        Self::try_from(u16::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}
