mod access;
mod automaticcriticalerroraction;
mod automaticrecoveryaction;
mod automaticshutdownaction;
mod automaticstartupaction;
mod availablerequestedstate;
mod backupintent;
mod cachingmode;
mod capturelivestate;
mod changedrangestream;
mod communicationstatus;
mod computersystemout;
mod concretejobmodificationevent;
mod consolemode;
mod consumervisibility;
mod copysnapshotconfiguration;
mod debugportenabledtype;
mod dedicated;
mod detailedstatus;
mod devicetype;
mod enableddefault;
mod enabledstate;
mod enhancedsessionmodestate;
mod enhancedsessiontransporttype;
mod filehandle;
mod format;
mod healthstate;
mod highmmiogapsize;
mod hostextentnameformat;
mod hostextentnamenamespace;
mod imagemanagementservice;
mod imagemanagementserviceout;
mod instanceid;
mod job;
mod jobout;
mod jobstate;
mod jobtype;
mod localorutctime;
mod lowmmiogapsize;
mod mappingbehavior;
mod networkbootprotocol;
mod operatingstatus;
mod operationalstatus;
mod path;
mod parentid;
mod pmemaddressabstractiontype;
mod percent;
mod powermanagementcapabilities;
mod primarystatus;
mod property;
mod recoveryaction;
mod replicationmode;
mod requestedstate;
mod resetcapability;
mod resilientchangetrackingid;
mod resourcetype;
mod result;
mod runday;
mod rundayofweek;
mod runmonth;
mod sequencenumber;
mod snapshotid;
mod snapshottype;
mod storageallocationsettingdata;
mod storageallocationsettingdataout;
mod storageqospolicyid;
mod tcpport;
mod transitioningstate;
mod transitioningtostate;
mod usersnapshottype;
mod version;
mod virtualdisk;
mod virtualdiskid;
mod virtualdiskrange;
mod virtualharddisksettingdata;
mod virtualharddisksettingdataout;
mod virtualsystemexportsettingdatain;
mod virtualsystemexportsettingdataout;
mod virtualsystemmanagementservice;
mod virtualsystemmanagementserviceout;
mod virtualsystemreferencepoint;
mod virtualsystemreferencepointout;
mod virtualsystemreferencepointservice;
mod virtualsystemsettingdata;
mod virtualsystemsettingdatain;
mod virtualsystemsettingdataout;
mod virtualsystemsnapshotservice;
mod virtualsystemsnapshotserviceout;
mod writehardeningmethod;
mod r#type;

pub(crate) use crate::model::VirtualMachine;
pub(crate) use crate::model::referencepointservice::ConsistencyLevel;
pub(crate) use crate::model::{ReferencePointId, VirtualMachineId};
use access::Access;
use automaticcriticalerroraction::AutomaticCriticalErrorAction;
use automaticrecoveryaction::AutomaticRecoveryAction;
use automaticshutdownaction::AutomaticShutdownAction;
use automaticstartupaction::AutomaticStartupAction;
pub(crate) use availablerequestedstate::AvailableRequestedState;
use backupintent::BackupIntent;
use cachingmode::CachingMode;
use capturelivestate::CaptureLiveState;
pub(crate) use communicationstatus::CommunicationStatus;
pub(crate) use computersystemout::ComputerSystemOut;
use concretejobmodificationevent::ConcreteJobModificationEvent;
use consolemode::ConsoleMode;
use consumervisibility::ConsumerVisibility;
pub(crate) use copysnapshotconfiguration::CopySnapshotConfiguration;
use debugportenabledtype::DebugPortEnabledType;
pub(crate) use dedicated::Dedicated;
pub(crate) use detailedstatus::DetailedStatus;
pub(crate) use devicetype::DeviceType;
pub(crate) use enableddefault::EnabledDefault;
pub(crate) use enabledstate::EnabledState;
pub(crate) use enhancedsessionmodestate::EnhancedSessionModeState;
use enhancedsessiontransporttype::EnhancedSessionTransportType;
pub(crate) use healthstate::HealthState;
use highmmiogapsize::HighMmioGapSize;
use hostextentnameformat::HostExtentNameFormat;
use hostextentnamenamespace::HostExtentNameNamespace;
pub(crate) use imagemanagementservice::ImageManagementService;
use imagemanagementserviceout::ImageManagementServiceOut;
use instanceid::InstanceId;
use job::{Job, method_return_value_description};
use jobout::JobOut;
use jobstate::JobState;
use jobtype::JobType;
use localorutctime::LocalOrUtcTime;
use lowmmiogapsize::LowMmioGapSize;
use mappingbehavior::MappingBehavior;
use networkbootprotocol::NetworkBootProtocol;
pub(crate) use operatingstatus::OperatingStatus;
pub(crate) use operationalstatus::OperationalStatus;
pub use path::Path;
use parentid::ParentId;
use pmemaddressabstractiontype::PmemAddressAbstractionType;
use percent::Percent;
pub(crate) use powermanagementcapabilities::PowerManagementCapabilities;
pub(crate) use primarystatus::PrimaryStatus;
use property::Property;
use recoveryaction::RecoveryAction;
pub(crate) use replicationmode::ReplicationMode;
pub(crate) use requestedstate::RequestedState;
pub(crate) use resetcapability::ResetCapability;
use resilientchangetrackingid::ResilientChangeTrackingId;
use resourcetype::ResourceType;
use result::Result as MethodResult;
use runday::RunDay;
use rundayofweek::RunDayOfWeek;
use runmonth::RunMonth;
use sequencenumber::SequenceNumber;
use snapshotid::SnapshotId;
pub(crate) use snapshottype::SnapshotType;
pub(crate) use storageallocationsettingdata::StorageAllocationSettingData;
use storageallocationsettingdataout::StorageAllocationSettingDataOut;
use storageqospolicyid::StorageQoSPolicyId;
use tcpport::TcpPort;
use transitioningstate::TransitioningState;
pub(crate) use transitioningtostate::TransitioningToState;
use usersnapshottype::UserSnapshotType;
use version::Version;
pub(crate) use virtualdisk::{VirtualDisk, VirtualDiskRange};
use virtualdiskid::VirtualDiskId;
pub(crate) use virtualharddisksettingdata::VirtualHardDiskSettingData;
use virtualharddisksettingdataout::VirtualHardDiskSettingDataOut;
pub(crate) use virtualsystemexportsettingdatain::VirtualSystemExportSettingDataIn;
use virtualsystemexportsettingdataout::VirtualSystemExportSettingDataOut;
pub(crate) use virtualsystemmanagementservice::VirtualSystemManagementService;
use virtualsystemmanagementserviceout::VirtualSystemManagementServiceOut;
pub(crate) use virtualsystemreferencepoint::VirtualSystemReferencePoint;
use virtualsystemreferencepointout::VirtualSystemReferencePointOut;
pub(crate) use virtualsystemreferencepointservice::{ReferencePointTypeIn, VirtualSystemReferencePointService, VirtualSystemReferencePointSettingDataIn};
pub(crate) use virtualsystemsettingdata::VirtualSystemSettingData;
pub(crate) use virtualsystemsettingdatain::VirtualSystemSettingDataIn;
use virtualsystemsettingdataout::VirtualSystemSettingDataOut;
pub(crate) use virtualsystemsnapshotservice::VirtualSystemSnapshotService;
use virtualsystemsnapshotserviceout::VirtualSystemSnapshotServiceOut;
use format::Format;
use changedrangestream::ChangedRangeStream;
use filehandle::FileHandle;
use r#type::Type;
use writehardeningmethod::WriteHardeningMethod;

// The standard WMI namespace for Hyper-V (v2)
pub const HYPER_V_NAMESPACE: &str = r"root\virtualization\v2";
