mod availablerequestedstate;
mod automaticcriticalerroraction;
mod automaticrecoveryaction;
mod automaticshutdownaction;
mod automaticstartupaction;
mod backupintent;
mod capturelivestate;
mod communicationstatus;
mod computersystemout;
mod concretejobmodificationevent;
mod copysnapshotconfiguration;
mod consolemode;
mod debugportenabledtype;
mod dedicated;
mod detailedstatus;
mod devicetype;
mod enableddefault;
mod enabledstate;
mod enhancedsessionmodestate;
mod enhancedsessiontransporttype;
mod healthstate;
mod highmmiogapsize;
mod instanceid;
mod job;
mod jobout;
mod jobstate;
mod jobtype;
mod localorutctime; 
mod lowmmiogapsize;
mod networkbootprotocol;
mod operatingstatus;
mod operationalstatus;
mod path;
mod percent;
mod powermanagementcapabilities;
mod primarystatus;
mod property;
mod recoveryaction;
mod referencepointtypein;
mod replicationmode;
mod resilientchangetrackingid;
mod result;
mod runmonth;
mod runday;
mod rundayofweek;
mod requestedstate;
mod resetcapability;
mod sequencenumber;
mod snapshottype;
mod tcpport;
mod transitioningstate;
mod transitioningtostate;
mod usersnapshottype;
mod version;
mod virtualdisk;
mod virtualdiskid;
mod virtualsystemexportsettingdatain;
mod virtualsystemexportsettingdataout;
mod virtualsystemmanagementservice;
mod virtualsystemmanagementserviceout;
mod virtualsystemreferencepoint;
mod virtualsystemreferencepointout;
mod virtualsystemreferencepointservice;
mod virtualsystemreferencepointserviceout;
mod virtualsystemreferencepointsettingdatain;
mod virtualsystemsnapshotservice;
mod virtualsystemsnapshotserviceout;
mod virtualsystemsettingdata;
mod virtualsystemsettingdatain;
mod virtualsystemsettingdataout;

pub(crate) use availablerequestedstate::AvailableRequestedState;
use automaticcriticalerroraction::AutomaticCriticalErrorAction;
use automaticrecoveryaction::AutomaticRecoveryAction;
use automaticshutdownaction::AutomaticShutdownAction;
use automaticstartupaction::AutomaticStartupAction;
use backupintent::BackupIntent;
use capturelivestate::CaptureLiveState;
pub(crate) use copysnapshotconfiguration::CopySnapshotConfiguration;
pub(crate) use communicationstatus::CommunicationStatus;
pub(crate) use computersystemout::ComputerSystemOut;
use concretejobmodificationevent::ConcreteJobModificationEvent;
pub(crate) use crate::model::{ConsistencyLevel, ReferencePointId, ReferencePointType, VirtualMachineId};
use consolemode::ConsoleMode;
use debugportenabledtype::DebugPortEnabledType;
pub(crate) use dedicated::Dedicated;
pub(crate) use detailedstatus::DetailedStatus;
pub(crate) use devicetype::DeviceType;
pub(crate) use enableddefault::EnabledDefault;
pub(crate) use enabledstate::EnabledState;
pub(crate) use enhancedsessionmodestate::EnhancedSessionModeState;
use enhancedsessiontransporttype::EnhancedSessionTransportType;
pub(crate) use healthstate::HealthState;
use highmmiogapsize::HighMmioGapSize;
use instanceid::InstanceId;
use job::Job;
use jobout::JobOut;
use jobstate::JobState;
use jobtype::JobType;
use localorutctime::LocalOrUtcTime;
use lowmmiogapsize::LowMmioGapSize;
use networkbootprotocol::NetworkBootProtocol;
pub(crate) use operatingstatus::OperatingStatus;
pub(crate) use operationalstatus::OperationalStatus;
pub use path::Path;
use percent::Percent;
pub(crate) use powermanagementcapabilities::PowerManagementCapabilities;
pub(crate) use primarystatus::PrimaryStatus;
use property::Property;
use recoveryaction::RecoveryAction;
use referencepointtypein::ReferencePointTypeIn;
pub(crate) use replicationmode::ReplicationMode;
pub(crate) use requestedstate::RequestedState;
pub(crate) use resetcapability::ResetCapability;
use resilientchangetrackingid::ResilientChangeTrackingId;
use result::Result as MethodResult;
use runmonth::RunMonth;
use runday::RunDay;
use rundayofweek::RunDayOfWeek;
use sequencenumber::SequenceNumber;
pub(crate) use snapshottype::SnapshotType;
use tcpport::TcpPort;
use transitioningstate::TransitioningState;
pub(crate) use transitioningtostate::TransitioningToState;
use usersnapshottype::UserSnapshotType;
use version::Version;
use virtualdiskid::VirtualDiskId;
pub(crate) use crate::model::VirtualMachine;
pub(crate) use virtualsystemexportsettingdatain::VirtualSystemExportSettingDataIn;
use virtualsystemexportsettingdataout::VirtualSystemExportSettingDataOut;
pub (crate) use virtualsystemmanagementservice::VirtualSystemManagementService;
use virtualsystemmanagementserviceout::VirtualSystemManagementServiceOut;
pub(crate) use virtualsystemreferencepoint::VirtualSystemReferencePoint;
use virtualsystemreferencepointout::VirtualSystemReferencePointOut;
pub(crate) use virtualsystemreferencepointservice::VirtualSystemReferencePointService;
use virtualsystemreferencepointserviceout::VirtualSystemReferencePointServiceOut;
pub(crate) use virtualsystemreferencepointsettingdatain::VirtualSystemReferencePointSettingDataIn;
pub(crate) use virtualsystemsnapshotservice::VirtualSystemSnapshotService;
use virtualsystemsnapshotserviceout::VirtualSystemSnapshotServiceOut;
pub(crate) use virtualsystemsettingdata::VirtualSystemSettingData;
pub(crate) use virtualsystemsettingdatain::VirtualSystemSettingDataIn;
use virtualsystemsettingdataout::VirtualSystemSettingDataOut;

// The standard WMI namespace for Hyper-V (v2)
pub const HYPER_V_NAMESPACE: &str = r"root\virtualization\v2";
