#[derive(Debug, Clone)]
pub(crate) enum ResourceType {
    Other,
    ComputerSystem,
    Processor,
    Memory,
    IdeController,
    ParallelScsiHba,
    FcHba,
    IscsiHba,
    IbHca,
    EthernetAdapter,
    OtherNetworkAdapter,
    IoSlot,
    IoDevice,
    DisketteDrive,
    CdDrive,
    DvdDrive,
    DiskDrive,
    TapeDrive,
    StorageExtent,
    OtherStorageDevice,
    SerialPort,
    ParallelPort,
    UsbController,
    GraphicsController,
    Ieee1394Controller,
    PartitionableUnit,
    BasePartitionableUnit,
    PowerSupply,
    CoolingDevice,
    EthernetSwitchPort,
    LogicalDisk,
    StorageVolume,
    EthernetConnection,
    Reserved(u16),
}

impl TryFrom<u16> for ResourceType {
    type Error = &'static str;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Ok(match value {
            1 => Self::Other,
            2 => Self::ComputerSystem,
            3 => Self::Processor,
            4 => Self::Memory,
            5 => Self::IdeController,
            6 => Self::ParallelScsiHba,
            7 => Self::FcHba,
            8 => Self::IscsiHba,
            9 => Self::IbHca,
            10 => Self::EthernetAdapter,
            11 => Self::OtherNetworkAdapter,
            12 => Self::IoSlot,
            13 => Self::IoDevice,
            14 => Self::DisketteDrive,
            15 => Self::CdDrive,
            16 => Self::DvdDrive,
            17 => Self::DiskDrive,
            18 => Self::TapeDrive,
            19 => Self::StorageExtent,
            20 => Self::OtherStorageDevice,
            21 => Self::SerialPort,
            22 => Self::ParallelPort,
            23 => Self::UsbController,
            24 => Self::GraphicsController,
            25 => Self::Ieee1394Controller,
            26 => Self::PartitionableUnit,
            27 => Self::BasePartitionableUnit,
            28 => Self::PowerSupply,
            29 => Self::CoolingDevice,
            30 => Self::EthernetSwitchPort,
            31 => Self::LogicalDisk,
            32 => Self::StorageVolume,
            33 => Self::EthernetConnection,
            value => Self::Reserved(value),
        })
    }
}
