use serde::Deserialize;

#[derive(Debug, Deserialize)]
#[allow(non_snake_case)]
#[serde(rename = "Msvm_StorageAllocationSettingData")]
pub(crate) struct StorageAllocationSettingDataOut {
    pub(super) Access: Option<u16>,
    pub(super) Address: Option<String>,
    pub(super) AddressOnParent: Option<String>,
    pub(super) AllocationUnits: String,
    pub(super) AutomaticAllocation: bool,
    pub(super) AutomaticDeallocation: bool,
    pub(super) CachingMode: Option<u16>,
    pub(super) Caption: String,
    pub(super) Connection: Option<Vec<String>>,
    pub(super) ConsumerVisibility: Option<u16>,
    pub(super) Description: String,
    pub(super) ElementName: String,
    pub(super) HostExtentName: Option<String>,
    pub(super) HostExtentNameFormat: Option<u16>,
    pub(super) HostExtentNameNamespace: Option<u16>,
    pub(super) HostExtentStartingAddress: Option<u64>,
    pub(super) HostResource: Option<Vec<String>>,
    pub(super) HostResourceBlockSize: Option<u64>,
    pub(super) IgnoreFlushes: bool,
    pub(super) InstanceID: String,
    pub(super) IOPSAllocationUnits: String,
    pub(super) IOPSLimit: Option<u64>,
    pub(super) IOPSReservation: Option<u64>,
    pub(super) Limit: Option<u64>,
    pub(super) MappingBehavior: Option<u16>,
    pub(super) OtherHostExtentNameFormat: Option<String>,
    pub(super) OtherHostExtentNameNamespace: Option<String>,
    pub(super) OtherResourceType: Option<String>,
    pub(super) Parent: Option<String>,
    pub(super) PersistentReservationsSupported: bool,
    pub(super) PoolID: Option<String>,
    pub(super) Reservation: Option<u64>,
    pub(super) ResourceSubType: Option<String>,
    pub(super) ResourceType: Option<u16>,
    pub(super) SnapshotId: String,
    pub(super) StorageQoSPolicyID: Option<String>,
    pub(super) VirtualQuantity: Option<u64>,
    pub(super) VirtualQuantityUnits: String,
    pub(super) VirtualResourceBlockSize: Option<u64>,
    pub(super) Weight: Option<u32>,
    pub(super) WriteHardeningMethod: Option<u16>,
}
