use super::*;
use serde::{Deserialize, Deserializer};
use std::path::PathBuf;

#[derive(Clone, Debug)]
pub(crate) struct StorageAllocationSettingData {
    pub(crate) access: Option<Access>,
    pub(crate) address: Option<String>,
    pub(crate) address_on_parent: Option<String>,
    pub(crate) allocation_units: String,
    pub(crate) automatic_allocation: bool,
    pub(crate) automatic_deallocation: bool,
    pub(crate) caching_mode: CachingMode,
    pub(crate) caption: String,
    pub(crate) connection: Vec<String>,
    pub(crate) consumer_visibility: ConsumerVisibility,
    pub(crate) description: String,
    pub(crate) element_name: String,
    pub(crate) host_extent_name: Option<String>,
    pub(crate) host_extent_name_format: Option<HostExtentNameFormat>,
    pub(crate) host_extent_name_namespace: Option<HostExtentNameNamespace>,
    pub(crate) host_extent_starting_address: Option<u64>,
    pub(crate) host_resource: Vec<PathBuf>,
    pub(crate) host_resource_block_size: Option<u64>,
    pub(crate) ignore_flushes: bool,
    pub(crate) instance_id: InstanceId,
    pub(crate) iops_allocation_units: String,
    pub(crate) iops_limit: u64,
    pub(crate) iops_reservation: u64,
    pub(crate) limit: u64,
    pub(crate) mapping_behavior: Option<MappingBehavior>,
    pub(crate) other_host_extent_name_format: Option<String>,
    pub(crate) other_host_extent_name_namespace: Option<String>,
    pub(crate) other_resource_type: Option<String>,
    pub(crate) parent: Path,
    pub(crate) persistent_reservations_supported: bool,
    pub(crate) pool_id: String,
    pub(crate) reservation: u64,
    pub(crate) resource_sub_type: String,
    pub(crate) resource_type: ResourceType,
    pub(crate) snapshot_id: SnapshotId,
    pub(crate) storage_qos_policy_id: StorageQoSPolicyId,
    pub(crate) virtual_quantity: u64,
    pub(crate) virtual_quantity_units: String,
    pub(crate) virtual_resource_block_size: Option<u64>,
    pub(crate) weight: u32,
    pub(crate) write_hardening_method: WriteHardeningMethod,
}

impl<'de> Deserialize<'de> for StorageAllocationSettingData {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let output = StorageAllocationSettingDataOut::deserialize(deserializer)?;
        Ok(Self {
            access: output.Access.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?,
            address: output.Address,
            address_on_parent: output.AddressOnParent,
            allocation_units: output.AllocationUnits,
            automatic_allocation: output.AutomaticAllocation,
            automatic_deallocation: output.AutomaticDeallocation,
            caching_mode: output.CachingMode.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?.unwrap_or(CachingMode::Unknown),
            caption: output.Caption,
            connection: output.Connection.unwrap_or_default(),
            consumer_visibility: output.ConsumerVisibility.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?.unwrap_or(ConsumerVisibility::Unknown),
            description: output.Description,
            element_name: output.ElementName,
            host_extent_name: output.HostExtentName,
            host_extent_name_format: output.HostExtentNameFormat.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?,
            host_extent_name_namespace: output.HostExtentNameNamespace.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?,
            host_extent_starting_address: output.HostExtentStartingAddress,
            host_resource: output.HostResource.unwrap_or_default().into_iter().map(PathBuf::from).collect(),
            host_resource_block_size: output.HostResourceBlockSize,
            ignore_flushes: output.IgnoreFlushes,
            instance_id: output.InstanceID.into(),
            iops_allocation_units: output.IOPSAllocationUnits,
            iops_limit: output.IOPSLimit.unwrap_or_default(),
            iops_reservation: output.IOPSReservation.unwrap_or_default(),
            limit: output.Limit.unwrap_or_default(),
            mapping_behavior: output.MappingBehavior.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?,
            other_host_extent_name_format: output.OtherHostExtentNameFormat,
            other_host_extent_name_namespace: output.OtherHostExtentNameNamespace,
            other_resource_type: output.OtherResourceType,
            parent: output.Parent.unwrap_or_default().into(),
            persistent_reservations_supported: output.PersistentReservationsSupported,
            pool_id: output.PoolID.unwrap_or_default(),
            reservation: output.Reservation.unwrap_or_default(),
            resource_sub_type: output.ResourceSubType.unwrap_or_default(),
            resource_type: output.ResourceType.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?.unwrap_or(ResourceType::Reserved(0)),
            snapshot_id: SnapshotId::parse_str(&output.SnapshotId).map_err(serde::de::Error::custom)?,
            storage_qos_policy_id: output.StorageQoSPolicyID.map(|value| StorageQoSPolicyId::parse_str(&value)).transpose().map_err(serde::de::Error::custom)?.unwrap_or_default(),
            virtual_quantity: output.VirtualQuantity.unwrap_or_default(),
            virtual_quantity_units: output.VirtualQuantityUnits,
            virtual_resource_block_size: output.VirtualResourceBlockSize,
            weight: output.Weight.unwrap_or_default(),
            write_hardening_method: output.WriteHardeningMethod.map(TryInto::try_into).transpose().map_err(serde::de::Error::custom)?.unwrap_or(WriteHardeningMethod::Default),
        })
    }
}
